config/routes.rb
Rails.application.routes.draw do
  resources :products
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :requests
  get 'welcome/index'
  root 'welcome#index'
  get 'search', to: 'search#search'

  resources :gbooks
  resources :cbooks
  resources :sbooks
  resources :abooks


  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
   get '/cart/tracking', to: 'orders#show', as: :tracking


  get "welcome/academics"
  get "welcome/school"
  get "welcome/general"
  get "welcome/competetive"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sbook.rb
class Sbook < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :previewo, PreviewoUploader
	mount_uploader :previewt, PreviewtUploader
	mount_uploader :previewth, PreviewthUploader
	validates :description, presence: true, length: { maximum: 600 }
end

app/controllers/sbooks_controller.rb
class SbooksController < ApplicationController
  before_action :set_sbook, only: [:show, :edit, :update, :destroy]

  # GET /sbooks
  # GET /sbooks.json
  def index
    @sbooks = Sbook.all
  end

  # GET /sbooks/1
  # GET /sbooks/1.json
  def show
  end

  # GET /sbooks/new
  def new
    @sbook = Sbook.new
  end

  # GET /sbooks/1/edit
  def edit
  end

  # POST /sbooks
  # POST /sbooks.json
  def create
    @sbook = Sbook.new(sbook_params)

    respond_to do |format|
      if @sbook.save
        format.html { redirect_to @sbook, notice: 'Sbook was successfully created.' }
        format.json { render :show, status: :created, location: @sbook }
      else
        format.html { render :new }
        format.json { render json: @sbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sbooks/1
  # PATCH/PUT /sbooks/1.json
  def update
    respond_to do |format|
      if @sbook.update(sbook_params)
        format.html { redirect_to @sbook, notice: 'Sbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @sbook }
      else
        format.html { render :edit }
        format.json { render json: @sbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sbooks/1
  # DELETE /sbooks/1.json
  def destroy
    @sbook.destroy
    respond_to do |format|
      format.html { redirect_to sbooks_url, notice: 'Sbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sbook
      @sbook = Sbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sbook_params
      params.require(:sbook).permit(:title, :description, :sdescription, :image, :previewo, :previewt, :previewth, :price, :offerprice, :coupon, :author, :publication, :saving, :off)
    end
end

app/helpers/sbooks_helper.rb
module SbooksHelper
end

app/views/sbooks/_form.html.erb
<%= form_with(model: sbook, local: true) do |form| %>
  <% if sbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sbook.errors.count, "error") %> prohibited this sbook from being saved:</h2>

      <ul>
      <% sbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :sbook_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :sbook_description %>
  </div>

  <div class="field">
    <%= form.label :sdescription %>
    <%= form.text_field :sdescription, id: :sbook_sdescription %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :sbook_image %>
  </div>

  <div class="field">
    <%= form.label :previewo %>
    <%= form.file_field :previewo, id: :sbook_previewo %>
  </div>

  <div class="field">
    <%= form.label :previewt %>
    <%= form.file_field :previewt, id: :sbook_previewt %>
  </div>

  <div class="field">
    <%= form.label :previewth %>
    <%= form.file_field :previewth, id: :sbook_previewth %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :sbook_price %>
  </div>

  <div class="field">
    <%= form.label :offerprice %>
    <%= form.text_field :offerprice, id: :sbook_offerprice %>
  </div>

    <div class="field">
    <%= form.label :saving %>
    <%= form.text_field :saving %>
  </div>

  <div class="field">
    <%= form.label :off %>
    <%= form.text_field :off %>
  </div>

  <div class="field">
    <%= form.label :coupon %>
    <%= form.text_field :coupon, id: :sbook_coupon %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :sbook_author %>
  </div>

  <div class="field">
    <%= form.label :publication %>
    <%= form.text_field :publication, id: :sbook_publication %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sbooks/_sbook_related.html.erb
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="/assets/sbooks.scss">
</head>

<body>



  <main>




    <div class="container-fluid bg-cover">
      <div class="container product-section-cover">

        <div class="row">


          
          <div class="col col-md-4 col-sm-6">
              <div class="product-grid">
                <div class="image">
                  <a href="#">
                    <img src= "<%= @sbook.image %>" alt="<%= @sbook.title %> 's image" class="img-fluid">
                    <span class="overlay">
                        <span class="product-details">
                          View Details
                        </span>
                    </span>
                  </a>
                </div>
                <div class="product-discription py-3">
                <h4 class="text-center"><%= @sbook.title %></h4>
                <p class="text-center"><small><%= @sbook.sdescription %></small></p>
                <span class="product-price">
                <p class="text-center d-inline">Price: <%= @sbook.price %></p><i class="fa fa-heart d-inline" aria-hidden="true"></i>
                </span>
                </div>
                <div class="product-btn py-2 text-center">
                <a href="#" class="btn btn-lg " role="button" aria-pressed="true">ADD TO CART</a>
                </div>
              </div>
          </div>
        

      </div>
    </div>


  </main>

</body>

app/views/sbooks/edit.html.erb
<h1>Editing Sbook</h1>

<%= render 'form', sbook: @sbook %>

<%= link_to 'Show', @sbook %> |
<%= link_to 'Back', sbooks_path %>

app/views/sbooks/index.html.erb
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="/assets/sbooks.scss">
</head>

<body>

  <!--Carousel -->
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/assets/bg-1.jpg" style="height:250px;" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/bg-2.jpg" style="height:250px;" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/bg-3.jpg" style="height:250px;" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>




<div class="container-fluid section-title ">
      <div class="container py-4">
        <h3 class="text-center">All Academic Books</h3>
        <hr class="title-border">
        <p class="text-justify text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi facilis omnis asperiores atque rerum quam. Alias voluptatem aspernatur voluptate nemo perspiciatis ullam cum in. Enim, inventore sunt qui corporis molestias.</p>
      </div>
</div>




  <main>




    <div class="container-fluid bg-cover">
      <div class="container product-section-cover">

        <div class="row">


          <% @sbooks.each do |sbook| %>
          <div class="col col-md-4 col-sm-6">
              <div class="product-grid">
                <div class="image">
                    <img src= "<%= sbook.image %>" alt="<%= sbook.title %> 's image" class="img-fluid">
                    <span class="overlay">
                        <span class="product-details">
                           <%= link_to "View Details", sbook, class: "linky" %>
                        </span>
                    </span>
                </div>
                <div class="product-discription py-3">
                <h4 class="text-center"><%= sbook.title %></h4>
                <p class="text-center"><small><%= sbook.sdescription %></small></p>
                <span class="product-price">
                <p class="text-center d-inline">Price: <%= sbook.price %></p><i class="fa fa-heart d-inline" aria-hidden="true"></i>
                </span>
                </div>
                <div class="product-btn py-2 text-center">
                <a href="#" class="btn btn-lg " role="button" aria-pressed="true">ADD TO CART</a>
                </div>
              </div>
          </div>
          <% end %>

      </div>
    </div>


  </main>

</body>

app/views/sbooks/new.html.erb
<h1>New Sbook</h1>

<%= render 'form', sbook: @sbook %>

<%= link_to 'Back', sbooks_path %>