config/routes.rb
Rails.application.routes.draw do
  resources :products
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :requests
  get 'welcome/index'
  root 'welcome#index'
  get 'search', to: 'search#search'

  resources :gbooks
  resources :cbooks
  resources :sbooks
  resources :abooks


  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
   get '/cart/tracking', to: 'orders#show', as: :tracking


  get "welcome/academics"
  get "welcome/school"
  get "welcome/general"
  get "welcome/competetive"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :phone, :address, :bname, :author, :info)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
            <div class="col-md-1"></div>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

    <link rel="stylesheet" href="/assets/request.scss">

  </head>
  <body>

    <div class="section-header">
        <div class="row">
            <div class="col-md-7 d-none d-md-block">
                <div class="texts">
                    <div class="text1">
                        <h1>Buy Your Books</h1>
                    </div>

                    <div class="text2">
                        <p class="h4">Request any book you want, we will find it and deliver it to you.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-transparent py-5">
                    <p class="h1 text-center">Request A Book</p>
                    <%= form_with(model: request, local: true) do |form| %>
                    <div class="form-group">
                        <%= form.text_field :name, id: :request_name , placeholder: "Your Full Name"%>
                    </div>

                    <div class="form-group">
                            <%= form.text_field :phone, id: :request_phone, placeholder: "Your Valid Mobile Number" %>
                    </div>

                    <div class="form-group">
                            <%= form.text_field :phone, id: :request_phone, placeholder: "Your Email Address" %>
                    </div>

                    <div class="form-group">
                            <%= form.text_field :address, id: :request_address, placeholder: "Your Complete Address" %>
                    </div>

                    <div class="form-group">
                            <%= form.text_field :bname, id: :request_bname, placeholder: "Name Of The Book" %>
                    </div>
                    <div class="form-group">
                            <%= form.text_field :author, id: :request_author, placeholder: "Name Of The author" %>
                    </div>
                    <div class="form-group">
                            <%= form.text_field :info, id: :request_info, placeholder: "Name of Publisher" %>
                    </div>

                    <div class="form-group">
                            <%= form.text_field :info, placeholder: "Quantity" %>
                    </div>
                    <br />


                    <div class="captcha">
                        <%= form.submit "Submit Request", class: "button" %>
                    </div>

                    <% end %>
            </div>
            </div>
        </div>
    </div>


    <div class="section-work">
        <div class="row">
            <div class="col-md-3">
                <div class="text-overlay">
                    <img src="/assets/request.png" alt="A" class="img-fluid" style="height:150px; width:150px;">
                    <div class="text">
                        <h4>Request:</h4>
                        <p class="h5">You add a request to find a book.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="text-overlay">
                    <img src="/assets/market.png" alt="B" class="img-fluid" style="height:150px; width:150px;">
                    <div class="text">
                        <h4>Search:</h4>
                        <p class="h5">We get the request and start searching the market.</p>
                    </div>
                </div>
            </div>

                <div class="col-md-3">
                    <div class="text-overlay">
                        <img src="/assets/deliver.png" alt="C" class="img-fluid" style="height:150px; width:150px;">
                        <div class="text">
                            <h4>Deliver:</h4>
                            <p class="h5">We find the book and deliver it to you.</p>
                        </div>
                    </div>
                </div>

                    <div class="col-md-3">
                        <div class="text-overlay">
                            <img src="/assets/satisfaction.png" alt="D" class="img-fluid" style="height:150px; width:150px;">
                            <div class="text">
                                <h4>Satisfaction:</h4>
                                <p class="h5">You saved your time and got your book without any hasle.</p>
                            </div>
                        </div>
                    </div>
        </div>
    </div>

    <div class="section-text-work mt-4">
        <h1 class="text-center large-text">
            Free Delivery*
        </h1>
        <p class="text-center">*Conditions Apply</p>

        <p class="h3 text-center my-5"><span class="h1">BuyYourBooks</span>
        India&apos;s first Online Book Market, Where You can Request Your Books.
        </p>
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Bname</th>
      <th>Author</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.phone %></td>
        <td><%= request.address %></td>
        <td><%= request.bname %></td>
        <td><%= request.author %></td>
        <td><%= request.info %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<div class="text-center">
<h1>New Request</h1>
</div>

<%= render 'form', request: @request %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>
<link rel="stylesheet" href="/assets/request.scss">


<div class="section-header" style="height:400px;">
        <div class="row">
            <div class="col-md-7 d-none d-md-block">
                <div class="texts">
                    <div class="text7">
                        <h1 style="font-size: 48px;">Thanks!</h1>
                    </div>

                    <div class="text8">
                        <p class="h4" style="font-size: 32px;">We have recived your request and one of us will contact you shortly.</p>
                    </div>
                    <%= link_to 'Edit', edit_request_path(@request), class: "btn btn-primary" %> |
<%= link_to 'Back', requests_path, class: "btn btn-success" %>
                </div>
            </div>
        </div>
    </div>

<style>
.text7 {
    font-family: 'Dancing Script', cursive;
    position: absolute;
    top: 90%;
    left: 50%;
    text-align: center;
    transform: translate(-30%, -30%);
    color: white;
    padding-top: 90px;

}
.text8 {
    font-family: 'Dancing Script', cursive;
    position: absolute;
    top: 40%;
    left: 50%;
    text-align: center;
    transform: translate(-30%, -30%);
    color: white;
    padding-top: 180px;

}
</style>