config/routes.rb
Rails.application.routes.draw do
  resources :products
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :requests
  get 'welcome/index'
  root 'welcome#index'
  get 'search', to: 'search#search'

  resources :gbooks
  resources :cbooks
  resources :sbooks
  resources :abooks


  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
   get '/cart/tracking', to: 'orders#show', as: :tracking


  get "welcome/academics"
  get "welcome/school"
  get "welcome/general"
  get "welcome/competetive"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abook.rb
class Abook < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :previewo, PreviewoUploader
	mount_uploader :previewt, PreviewtUploader
	mount_uploader :previewth, PreviewthUploader
	validates :description, presence: true, length: { maximum: 600 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cbook.rb
class Cbook < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :previewo, PreviewoUploader
	mount_uploader :previewt, PreviewtUploader
	mount_uploader :previewth, PreviewthUploader
	validates :description, presence: true, length: { maximum: 600 }
end

app/models/gbook.rb
class Gbook < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :previewo, PreviewoUploader
	mount_uploader :previewt, PreviewtUploader
	mount_uploader :previewth, PreviewthUploader
	validates :description, presence: true, length: { maximum: 600 }
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product

end

app/models/product.rb
require 'elasticsearch/model'
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :previewo, PreviewoUploader
	mount_uploader :previewt, PreviewtUploader
	mount_uploader :previewth, PreviewthUploader
	validates :description, presence: true, length: { maximum: 600 }
include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
end

Product.import force:true

@products = Product.search('foobar').records

app/models/request.rb
class Request < ApplicationRecord
end

app/models/sbook.rb
class Sbook < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :previewo, PreviewoUploader
	mount_uploader :previewt, PreviewtUploader
	mount_uploader :previewth, PreviewthUploader
	validates :description, presence: true, length: { maximum: 600 }
end

app/models/shopping_cart.rb
class ShoppingCart

  delegate :sub_total, to: :order

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token, status: 'cart') do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end
  
 def add_item(product_id:, quantity: 1)
product = Product.find(product_id)

order_item = order.items.find_or_initialize_by(
  product_id: product_id
)

order_item.price = product.price

order_item.quantity = quantity

ActiveRecord::Base.transaction do
  order_item.save
  update_sub_total!
end
end


  def remove_item(id:)
    ActiveRecord::Base.transaction do
      order.items.destroy(id)
      update_sub_total!
    end
  end

  private

  def update_sub_total!
    order.sub_total = order.items.sum('quantity*price')
    order.save
  end

end

app/controllers/abooks_controller.rb
class AbooksController < ApplicationController
  before_action :set_abook, only: [:show, :edit, :update, :destroy]

  # GET /abooks
  # GET /abooks.json
  def index
    @abooks = Abook.all
  end

  # GET /abooks/1
  # GET /abooks/1.json
  def show
  end

  # GET /abooks/new
  def new
    @abook = Abook.new
  end

  # GET /abooks/1/edit
  def edit
  end

  # POST /abooks
  # POST /abooks.json
  def create
    @abook = Abook.new(abook_params)

    respond_to do |format|
      if @abook.save
        format.html { redirect_to @abook, notice: 'Abook was successfully created.' }
        format.json { render :show, status: :created, location: @abook }
      else
        format.html { render :new }
        format.json { render json: @abook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abooks/1
  # PATCH/PUT /abooks/1.json
  def update
    respond_to do |format|
      if @abook.update(abook_params)
        format.html { redirect_to @abook, notice: 'Abook was successfully updated.' }
        format.json { render :show, status: :ok, location: @abook }
      else
        format.html { render :edit }
        format.json { render json: @abook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abooks/1
  # DELETE /abooks/1.json
  def destroy
    @abook.destroy
    respond_to do |format|
      format.html { redirect_to abooks_url, notice: 'Abook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abook
      @abook = Abook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abook_params
      params.require(:abook).permit(:title, :description, :sdescription, :image, :previewo, :previewt, :previewth, :price, :offerprice, :coupon, :author, :publication, :saving, :off)
    end
end

app/controllers/cbooks_controller.rb
class CbooksController < ApplicationController
  before_action :set_cbook, only: [:show, :edit, :update, :destroy]

  # GET /cbooks
  # GET /cbooks.json
  def index
    @cbooks = Cbook.all
  end

  # GET /cbooks/1
  # GET /cbooks/1.json
  def show
  end

  # GET /cbooks/new
  def new
    @cbook = Cbook.new
  end

  # GET /cbooks/1/edit
  def edit
  end

  # POST /cbooks
  # POST /cbooks.json
  def create
    @cbook = Cbook.new(cbook_params)

    respond_to do |format|
      if @cbook.save
        format.html { redirect_to @cbook, notice: 'Cbook was successfully created.' }
        format.json { render :show, status: :created, location: @cbook }
      else
        format.html { render :new }
        format.json { render json: @cbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cbooks/1
  # PATCH/PUT /cbooks/1.json
  def update
    respond_to do |format|
      if @cbook.update(cbook_params)
        format.html { redirect_to @cbook, notice: 'Cbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @cbook }
      else
        format.html { render :edit }
        format.json { render json: @cbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cbooks/1
  # DELETE /cbooks/1.json
  def destroy
    @cbook.destroy
    respond_to do |format|
      format.html { redirect_to cbooks_url, notice: 'Cbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cbook
      @cbook = Cbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cbook_params
      params.require(:cbook).permit(:title, :description, :sdescription, :image, :previewo, :previewt, :previewth, :price, :offerprice, :coupon, :author, :publication, :saving, :off)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@order = current_cart.order
	end

	def show
		@orders = Order.all
	end

	def create
		@order = current_cart.order
		if @order.update_attributes(order_params.merge(status:'open'))
			session[:cart_token] = nil
			redirect_to action: 'show'
		else
			render:new
		end
	end

	private
	def order_params
		params.require(:order).permit(:first_name, :las_name, :city, :mobile_number, :delivery_address, :email, :pincode, :tracking)
	end

end

app/helpers/abooks_helper.rb
module AbooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cbooks_helper.rb
module CbooksHelper
end

app/helpers/gbooks_helper.rb
module GbooksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sbooks_helper.rb
module SbooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/orders/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/assets/checkout.css">
    <title>Check Out</title>
  </head>
  <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#"><img src="/assets/logo.png" alt="" class="img-fluid"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div>
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                                <i class="fa fa-cart-arrow-down d-block" aria-hidden="true"></i>
                        <p><span class="text-color">Cart ------------ Delivery &amp; Billing Address ------------ </span>
                         Payment</p>
                    </li>
                    <li class="nav-item">
                        <div class="user">
                            <span class="h4"> Hello</span>
                        </div>
                    </li>
                  </ul>
                  
                </div>
              </nav>

        <div class="container mt-5">
            <div class="row">
                <div class="col col-md-8">
                    <div class="order-summary">
                            <div id="accordion">
                                    <div class="card mb-1">
                                      <div class="card-header" id="summary">
                                        <h5 class="mb-0">
                                          <button class="btn" data-toggle="collapse" data-target="#one" aria-expanded="true" aria-controls="one">
                                                <strong>Need Help?</strong>
                                                <span>(<%= link_to pluralize(current_cart.items_count, 'item'), cart_path %>)</span>
                                          </button>
                                        </h5>
                                      </div>
                                  
                                      <div id="one" class="collapse" aria-labelledby="summary" data-parent="#accordion">
                                        <div class="card-body">
                                              <div class="container">
                                                  <div class="col col-md-8">
                                                    <div class="box"> 
                                                        <div class="row">
                                                                <div class="col-md-5">
                                                                    <img src="/assets/help.png" alt="" class="img-fluid">
                                                                </div>
                                                                <div class="col col-md-7">
                                                                    <ul>
                                                                        <li>Need Help With Delivery.</li>
                                                                        <li>If you need any help regarding delivery.</li>
                                                                        <li><span class="text-color"><a href="/welcome/contact">Contact Us</a></span></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                    </div>

                                                  </div>
                                              </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                    </div>

                    <div class="form-checkOut">
                            <div id="accordion">
                                    <div class="card">
                                      <div class="card-header" id="form-checkOut">
                                        <h5 class="mb-0">
                                          <button class="btn" data-toggle="collapse" data-target="#two" aria-expanded="true" aria-controls="two">
                                                <strong class="text-uppercase">Shipping &amp; Billing Details</strong>
                                          </button>
                                        </h5>
                                      </div>
                                  
                                      <div id="two" class="collapse show" aria-labelledby="form-checkOut" data-parent="#accordion">
                                        <div class="card-body">
                                                
                                                  <%= form_for @order, url: checkout_path do |f| %>
                                                        <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          <label for="exampleFormControlInput1">First Name</label>
                                                          <%= f.text_field :first_name, autofocus: true, placeholder: "Your First Name" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          <label for="exampleFormControlInput1">Last Name</label>
                                                          <%= f.text_field :last_name, autofocus: true, placeholder: "Your Last Name" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          <label for="exampleFormControlInput1">Mobile</label>
                                                          <%= f.text_field :mobile_number, autofocus: true, placeholder: "Your Valid Mobile Number" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          <label for="exampleFormControlInput1">Email</label>
                                                          <%= f.text_field :email, autofocus: true, placeholder: "Your Email Address" %>
                                                        </div>
                                                    </div>
                                                        <div class="form-group">
                                                                <div class="d-flex justify-content-between">
                                                          <label for="exampleFormControlTextarea1">Address</label>
                                                          <%= f.text_field :delivery_address, autofocus: true, placeholder: "Complete Delivery Addresss" %>
                                                        </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          <label for="exampleFormControlInput1">City</label>
                                                          <%= f.text_field :city, autofocus: true, placeholder: "Delivery City" %>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          <label for="exampleFormControlInput1">Pincode</label>
                                                          <%= f.text_field :pincode, autofocus: true, placeholder: "Pincode" %>
                                                        </div>
                                                    </div>
                                                        <div class="form-check mb-2">
                                                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                                                <label class="form-check-label" for="exampleCheck1">Billing Address is same as Shipping Address</label>
                                                              </div>
                                                              <%= f.submit "Save & Continue", class: "btn" %>
                                                              <% end %>
                                                      
                                        </div>
                                      </div>
                                    </div>
                                    </div>
                    </div>

                </div>
                <div class="col col-md-4">
                    <div class="box">
                        <ul class="d-flex justify-content-between">
                            <li>
                                <p>Item Total</p>
                            </li>
                            <li>
                                <strong>Rs. <%= current_cart.sub_total %></strong>
                            </li>
                        </ul>
                        <ul class="d-flex justify-content-between">
                                <li>
                                    <p>Shipping &amp; Handling <span class="text-color">(free)</span></p>
                                </li>
                                <li>
                                    <strong>Rs. <%= current_cart.sub_total %></strong>
                                </li>
                            </ul>
                            <hr>
                            <ul class="d-flex justify-content-between">
                                    <li>
                                        <p>You Pay
                                            <br>
                                            <span class="text-muted"><small>(Including all Taxes)</small></span>
                                        </p>
                                    </li>
                                    <li>
                                            <strong>Rs. <%= current_cart.sub_total %></strong>
                                        </li>
                                </ul>
                    </div>
                </div>
            </div>
        </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/orders/show.html.erb
<div class="jumbotron text-xs-center">
  <h1 class="display-3">Thank You!</h1>
  <p class="lead"><strong>We Wil contact you</strong> When your order will be dispatched from our warehouse.</p>
  <hr>
  <p>
    Having trouble? <a href="/welcome/contact">Contact us</a>
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="/welcome/index" role="button">Continue to homepage</a>
  </p>
</div>